### ISSUE TITLE
"Recent Journals" text hard to read

### ISSUE THREAD

**Issue by Aceolu** [deaathtraap/Retro-FA-Skin#13]
When reading a journal, the section on the right that says "Recent Journals" has title text that is quite difficult to read, as even with the text shadow, the text color still near perfectly matches the background color
![image](https://github.com/deaathtraap/Retro-FA-Skin/assets/20609926/b56b4e98-fad6-4683-8fa2-718d1b510197)

**Comment by deaathtraap** [comment]
Fixed in 1.3.0
