### ISSUE TITLE
Title Previews are somewhat hard to see

### ISSUE THREAD

**Issue by Aceolu** [deaathtraap/Retro-FA-Skin#8]
When you hover your mouse over a picture to get the preview of the title, the font color makes it very hard to see.
![image](https://github.com/deaathtraap/Retro-FA-Skin/assets/20609926/b442e354-c4e5-4186-bca5-e91336323721)

**Comment by deaathtraap** [comment]
I think I could also make this look a lot nicer to look at than default FA. Perhaps moving it to the bottom, left-aligning it, and making it a subtle gradient fade instead of a dark box.

**Comment by deaathtraap** [comment]
I've gone ahead and restyled the hover information. This will be included in the next update.
![image](https://github.com/deaathtraap/Retro-FA-Skin/assets/142476306/69a12877-a196-49f7-8afd-9338ef82e9c5)
