### ISSUE TITLE
"Select all, Remove, and Nuke" options absent in New Submissons

### ISSUE THREAD

**Issue by Aceolu** [deaathtraap/Retro-FA-Skin#9]
The option to delete new submissions is absent in this section, while being present in Favorites, Journals, Comments, Etc
![image](https://github.com/deaathtraap/Retro-FA-Skin/assets/20609926/911f0db7-a587-426c-836a-940fc2aeb60b)

**Comment by deaathtraap** [comment]
I believe I've fixed this in the newest version. I'll close the issue when I publish it.

**Comment by deaathtraap** [comment]
Pushed the update that includes this fix, should show up in the latest version.
